//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJukeboxDbTools.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyJukeboxEntities : DbContext
    {
        public MyJukeboxEntities()
            : base("name=MyJukeboxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tCatalogs> tCatalogs { get; set; }
        public virtual DbSet<tFileInfos> tFileInfos { get; set; }
        public virtual DbSet<tGenres> tGenres { get; set; }
        public virtual DbSet<tInfos> tInfos { get; set; }
        public virtual DbSet<tMD5> tMD5 { get; set; }
        public virtual DbSet<tMedia> tMedia { get; set; }
        public virtual DbSet<tSongs> tSongs { get; set; }
    }
}
